Remove Ben Edgington
protocolguild/membership pull request #129
Opened 2024-01-21 17:52 UTC by benjaminion

So long, and thanks for all the fish :)

See [here](https://x.com/benjaminion_xyz/status/1749127053306138985) for further info.

2024-01-22 02:58 UTC, rolfyone approved these changes
LGTM

2024-01-22 13:01 UTC, dapplion requested changes
😢  you'll be missed!

2024-01-22 13:53 UTC, lightclient approved these changes
So long Ben! Thank you for your work!

2024-01-23 15:19 UTC, LukaszRozmej approved these changes

2024-01-23 17:03 UTC, merged